base_directory: C:\Users\NXTWAVE\Downloads\Smart Regional Office Accessibility
best_model: Decision Tree
dataset_path: C:\Users\NXTWAVE\Downloads\Smart Regional Office Accessibility\contact_details_of_regional_branch_offices_of_tiic_31_12_2019.csv
feature_columns:
- Regional_and_Branch_Code
- Names_of_Regional__Branch__Satellite_Offices
- Designation
- District
- Office_Type
- Pincode_Numeric
- Phone_Count
- Has_Email
- Estimated_Business_Density
- Estimated_MSME_Count
- Estimated_Distance_Index
- Estimated_Population_Coverage
h5_model: C:\Users\NXTWAVE\Downloads\Smart Regional Office Accessibility\regional_office_accessibility_model.h5
pkl_model: C:\Users\NXTWAVE\Downloads\Smart Regional Office Accessibility\regional_office_accessibility_model.pkl
project_name: Smart Regional Office Accessibility System
regression_target: Service_Demand_Score
target_column: Demand_Category
